### ISSUE TITLE
Code completion targets current module instead of aliased module of same name

### ISSUE THREAD

**Issue by xixa** [elixir-lsp/elixir_sense#69]
Example:
```Elixir
defmodule Project.Resolvers.Accounts do
  alias Project.Accounts
```
When using ```Accounts```, code completion will suggest functions from the module it's currently in instead of the defined alias.

I'm using elixir-ls on Neovim + ALE.

**Comment by lukaszsamson** [comment]
@xixa Could you verify that you are using https://github.com/elixir-lsp/elixir-ls fork? Original https://github.com/JakeBecker/elixir-ls is currently not maintained and uses an old version of elixir sense. The issue you are reporting was  fixed in https://github.com/elixir-lsp/elixir_sense/pull/18.

This is what I get on vscode with EllixirLS Fork plugin
<img width="485" alt="Screenshot 2019-12-30 at 10 41 50" src="https://user-images.githubusercontent.com/1078186/71578027-b67a2100-2af6-11ea-8054-0e537475e1f9.png">

**Comment by xixa** [comment]
That was it, thank you!
And sorry, I wasn't aware of this other repo.
