### ISSUE TITLE
Fix master

### ISSUE THREAD

**Issue by msaraiva** [elixir-lsp/elixir_sense#95]
Hi @lukaszsamson! 

I can see the last commit is breaking the build so I wonder if there's more work to be merged soon to fix that. Otherwise, I think the commit should be reverted so we can keep the master stable to accept other changes. I don't have much context regarding the last changes but in case you need any help, please let me know. I have some stuff I want to commit but I prefer to wait for the master to be stable before pushing them.

Cheers.

**Comment by lukaszsamson** [comment]
@msaraiva Sorry about that, I didn't notice I broke the build.
I indeed do have some work in progress that extends on the variable type static analyser but it's a POC at the moment. I'm going to need another week or two before it's ready. By that time you can treat master as stable and push your stuff.

Cheers

**Comment by msaraiva** [comment]
@lukaszsamson thanks!

The type tracking of variables is an awesome feature. There will be some edge cases but it can certainly be done for the most common scenarios. I'm excited to see you've started working on it. 🎉

Questions: 

1. What kind of variable you're going to keep track of? The ones defined as structs and literal maps?
1. Do you plan to use type specs to keep track of variables defined as function arguments?

**Comment by msaraiva** [comment]
Actually, forget my comment about maps. It would be a real pain since we can add/remove keys dynamically 🙂

**Comment by lukaszsamson** [comment]
I'm glad that you like it. Obviously, it's infeasible to cover all edge cases without fully compiling and evaluating the code. I only track types of maps, structs and atoms since those types can be used in call expressions and thats what most useful from code completions perspective.

As a first step I implemented type tracking for simple literal assignments and match expressions, e.g.
```
@attr String
var = %MyStruct{}
def fun(abc = %{x: _, y: _})
```
assignments referencing other vars/attributes, e.g.
```
@attr %{a: %{b: c}}
var = @attr
other = var
some = %{@attr | a: String}
```
and builtin sigils/structs
```
var = ~T[12:35]
range = 1..10
```
My current work in progress extends this to local and remote call expressions. I plan to cover:
1. map/struct field access, e.g.
```
map = %{a: %{b: c}}
sub = map.a
```
2. function calls with trivial return types defined in typespecs, e.g.
```
@spec some(any) :: Date.t
@spec fun :: %MyStruct{}
```

In the next steps we can add even more knowledge. Map module operations like put/merge/delete with literal keys are good candidates. The other is using typespecs to infere that if a fun taking type x arg was called with var then var is of type x.
